### ISSUE TITLE
Страница Список преподавателей

### ISSUE THREAD

**Issue by alexander-drach** [Aspirants-FS-FE/SheduliZZZer#12]
Добавить страницу "список преподавателей" и сверстать карточки преподавателей

**Comment by nionka** [comment]
![Screenshot_20201016-113352_Chrome](https://user-images.githubusercontent.com/50372965/96235480-875c6f80-0fa3-11eb-82c9-9ae2799534e1.jpg)
Эти поля - это просто список того  что есть у преподавателя или их можно будет прямо в карточке редактировать?

**Comment by nionka** [comment]
Или карточки получаются просто обзорными? Тогда может фамилию и имя сделать ссылкой на стр преподавателя?

**Comment by alexander-drach** [comment]
я бы сделал это все списком

общий класс .list уже описан для сброса стилей  <ul> и добавил бы модификатор .list_teachers, внутри него <li> ссылкой можно сделать аватарку и имя, т.е. одна карточка это информация о преподавателе на каких он курсах есть, какие лекции и дипломы ведет курсы, лекции и дипломы это тоже <ul>

**Comment by nionka** [comment]
Я запушила свою ветку! Посмотри перед PR
