### ISSUE TITLE
JS/develop a method on transform hamb-button

### ISSUE THREAD

**Issue by homutovan** [Aspirants-FS-FE/SheduliZZZer#34]
Требуется реализовать метод (видимо в классе Sidebar) для трансформации гамбургера в крест и обратно

**Comment by Helga-yalos** [comment]
начну с этого

**Comment by Helga-yalos** [comment]
залила ветку humb-button. Надо ли делать PR?

**Comment by homutovan** [comment]
Конечно)

**Comment by homutovan** [comment]
Done
