### ISSUE TITLE
fill a lession card for real data

### ISSUE THREAD

**Issue by homutovan** [Aspirants-FS-FE/SheduliZZZer#38]
Требуется заполнить карточку лекции реальными данными. На начальном этапе, возможно, даже руками. ссылка на данные: https://github.com/Aspirants-FS-FE/supporting

**Comment by Roman2517** [comment]
Я парсер не сделаю,но руками данные перенесу(чтоб процесс не тормозить)

**Comment by homutovan** [comment]
no longer relevant
