### ISSUE TITLE
invalide date in main widget

### ISSUE THREAD

**Issue by SemenovAV** [Aspirants-FS-FE/SheduliZZZer#65]
### Invalide date  in main witgets ###
При удалении любого из составляющих дату элемента, из поля выбора даты в таблице расписания, дата становится не действительной для всех ячеек таблицы с датой.
[ Скрин ](https://1drv.ms/u/s!AkaU3j-EcXQGgddbjvFeYRHGhVbHCw?e=88I2dh)
Исправить это можно только перезагрузкой страницы.

### Чтобы воспроизвести ошибку: ###

1. Переходим клавишей tab в поле выбора дат или кликаем мышкой в любую часть даты в этом поле.
2. Нажимаем клавишу Backspace
3. Наблюдаем ошибку 

### Ожидаемое поведение: ###
Удаление любой части даты не должно вызывать смену дат в виджете. 
Как минимум ожидается подсказка об ошибочно введенной дате.

**Desktop:**

- OS: Windows 10
- Browser: Microsoft Edge(Chromium)
- Version: Версия 86.0.622.51 (Официальная сборка) (64-разрядная версия)

**Comment by homutovan** [comment]
Done
